FROM node:18-alpine

ENV VITE_URL_API=http://localhost:8000/api
ENV VITE_TOKEN_NAME=ESURAT_API_TOKEN

# COPY . /var/www/html/app

# WORKDIR /var/www/html/app

# RUN npm install

# CMD ["npm", "run", "dev"]