version: "3.7"
services:
  unoserver:
    image: ghcr.io/unoconv/unoserver-docker
    container_name: unoserver
    restart: unless-stopped
    volumes:
      - ./backend/storage:/data
    tty: true
    stdin_open: true